spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gaegizo-database.czze61hirbwt.ap-northeast-2.rds.amazonaws.com/gaegizo
    username: admin
    password: aaaaaaaa

  jpa:
    hibernate:
      ddl-auto:   create
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace


